# Generated by Django 4.1.7 on 2023-02-28 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='muscle',
        ),
        migrations.AddField(
            model_name='exercise',
            name='body_part',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Core', 'Core'), ('Arms', 'Arms'), ('Back', 'Back'), ('Chest', 'Chest'), ('Legs', 'Legs'), ('Shoulders', 'Shoulders'), ('Other', 'Other'), ('Olympic', 'Olympic'), ('Full body', 'Full body'), ('Cardio', 'Cardio')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(blank=True, choices=[('Barbell', 'Barbell'), ('Dumbell', 'Dumbell'), ('Machine/Other', 'Machine/Other'), ('Weighted bodyweight', 'Weighted bodyweight'), ('Assisted body', 'Assisted body'), ('Reps only', 'Reps only'), ('Cardio exercice', 'Cardio exercice'), ('Duration', 'Duration')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstruction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseinstruction',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseinstruction',
            name='step_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
