# Generated by Django 4.1.3 on 2023-03-12 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_measurementtype_alter_exercise_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementtype',
            name='name',
            field=models.CharField(choices=[('Weight', 'Weight'), ('Caloric intake', 'Caloric intake'), ('Fat_percentage', 'Fat_percentage'), ('Neck', 'Neck'), ('Shoulders', 'Shoulders'), ('Chest', 'Chest'), ('Left bicep', 'Left bicep'), ('Right bicep', 'Right bicep'), ('Left forearm', 'Left forearm'), ('Right forearm', 'Right forearm'), ('Upper abs', 'Upper abs'), ('Waist', 'Waist'), ('Lower abs', 'Lower abs'), ('Hips', 'Hips'), ('Left thigh', 'Left thigh'), ('Right thigh', 'Right thigh'), ('Left calf', 'Left calf'), ('Right calf', 'Right calf')], max_length=50),
        ),
        migrations.AlterField(
            model_name='measurementtype',
            name='unit',
            field=models.CharField(choices=[('cm', 'cm'), ('kg', 'kg'), ('%', '%'), ('kcal', 'kcal')], max_length=10),
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('exercise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.exercise')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
