# Generated by Django 4.1.3 on 2023-03-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_measurementtype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttemplate',
            name='exercise',
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='exercise',
            field=models.ManyToManyField(blank=True, null=True, to='home.exercise'),
        ),
    ]
