# Generated by Django 4.1.3 on 2023-03-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_workouttemplate_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttemplate',
            name='exercise',
            field=models.ManyToManyField(blank=True, to='home.exercise'),
        ),
    ]
