# Generated by Django 4.1.7 on 2023-03-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_workouttemplate_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttemplate',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='workouttemplate',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exercise')),
                ('workout_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.workouttemplate')),
            ],
        ),
    ]
