# Generated by Django 4.1.7 on 2023-03-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_workouttemplate_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercise',
            old_name='reps',
            new_name='sets',
        ),
    ]
