# Generated by Django 4.1.7 on 2023-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_workoutsession_workoutsessionexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
