# Generated by Django 4.1.7 on 2023-03-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_workoutsession_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
