# Generated by Django 4.1.7 on 2023-03-28 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_set_reps_alter_set_weight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('exercise_session', 'set_number')},
        ),
    ]
