# Generated by Django 4.1.7 on 2023-03-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_set_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
