# Generated by Django 4.1.7 on 2023-04-03 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_workoutsession_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='exercise_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='home.workoutsessionexercise'),
        ),
    ]
