# Generated by Django 4.1.7 on 2023-04-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_exercise_is_custom_exercise_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
