# Generated by Django 4.1.3 on 2023-05-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_exercise_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='photo',
        ),
    ]
